import {
  getWeddingLayout,
  getWeddingStyle,
  getWeddingTypography,
  WEDDING_LAYOUT_VERSION,
  WEDDING_PROMPT_VERSION,
  WEDDING_STYLE_VERSION,
} from './config';
import { resolveWeddingDisplayTexts } from './composer';
import type { WeddingPromptRequest } from './types';

export function compileWeddingPrompt(input: WeddingPromptRequest) {
  const style = getWeddingStyle(input.style);
  const layout = getWeddingLayout(input.layout);
  const match = input.matchExample ?? null;
  const hasExample = Boolean(input.exampleImage);

  // Per-property wording. When the user flipped a property to
  // "match the example", the concrete value is replaced with a directive
  // to follow the reference image so the multimodal model can reconcile
  // them. Properties that the user *didn't* flag (or properties without
  // an example) still get the concrete text so the model has something
  // to work with.
  const flowersLine = match?.flowers
    ? 'Flowers: match the floral and botanical elements shown in the reference example image.'
    : `Flowers: ${input.flowers.filter(Boolean).join(', ') || 'subtle seasonal flowers'}.`;
  const personalElementsLine = match?.elements
    ? 'Personal elements: match the personal ornaments and motifs shown in the reference example image.'
    : `Personal elements: ${input.personalElements.filter(Boolean).join(', ') || 'no extra personal object'}.`;
  const paletteLine = match?.palette
    ? 'Palette: match the color palette of the reference example image exactly.'
    : `Palette: ${input.palette.join(', ')}.`;
  const borderLine =
    match?.border && hasExample
      ? 'Border / ornament: replicate the border shape, corner ornaments, and overall framing of the reference example image.'
      : null;

  // Lettering is now generated by the image model itself (no SVG
  // overlay). Spell out the exact inscriptions, their hierarchy, the
  // lettering style from the chosen pairing, and the position. Every
  // inscription is quoted so the model is expected to render the
  // exact casing character-for-character.
  const typography = getWeddingTypography(input.typography);
  const texts = resolveWeddingDisplayTexts(input);
  const inscriptionLines: string[] = [
    `Main inscription: "${texts.headline}" - the dominant element of the crest, centered in the composition.`,
  ];
  if (texts.names) {
    inscriptionLines.push(
      `Names line: "${texts.names}" - smaller, centered directly below the main inscription.`
    );
  }
  if (texts.date) {
    inscriptionLines.push(
      `Date line: "${texts.date}" - smallest, centered below the names line.`
    );
  }
  const typographySection = [
    'Typography - inscribe this lettering directly into the crest artwork as part of the illustration:',
    ...inscriptionLines,
    `Lettering style: ${typography.prompt}.`,
    'Text rules: render every inscription exactly as quoted, letter for letter, in the same casing; keep the lettering crisp, evenly spaced and elegantly typeset so it reads clearly against the surrounding artwork; include no other words, letters, numbers, dates, logos, watermarks or symbols anywhere else in the image.',
  ].join('\n');

  return [
    `Create a refined ${style.name.toLowerCase()} wedding crest illustration.`,
    `Visual medium: ${style.medium}.`,
    `Composition: ${layout.shape} arrangement, symmetrical balance, keeping the center of the composition clear and open so the lettering below sits prominently and reads cleanly.`,
    // The crest must float on transparency so it can be layered onto any
    // stationery surface. outputFormat is already PNG in the provider
    // adapter, so the model just needs to be told to use the alpha channel.
    'Background: fully transparent - render the crest artwork on a transparent background (PNG alpha channel) with no backdrop, no paper, no scenery, no fill color and no shadows or gradients behind the artwork.',
    flowersLine,
    personalElementsLine,
    `Wedding setting inspiration: ${input.location || 'a refined destination wedding'}${input.venue ? `, ${input.venue}` : ''}.`,
    paletteLine,
    `Complexity: ${input.complexity}.`,
    // Border is a single line because it doesn't have a "concrete value"
    // by default - the user always picked (or skipped) a specific frame
    // and we kept that frameId for the SVG composer. The "match example"
    // variant is the only time the prompt itself has to drive the border.
    ...(borderLine ? [borderLine] : []),
    typographySection,
    // Reference images travel in two flavors: the example (match its
    // visual language) and personal photos (paint the subject). The
    // first reference image is always the example when both are present;
    // the prompt makes that ordering explicit so the model doesn't
    // confuse them.
    ...(hasExample || (input.personalImages ?? []).length > 0
      ? [
          `Reference images: ${[
            hasExample ? '1 example crest' : '',
            ...((input.personalImages ?? []).length > 0
              ? [
                  `${(input.personalImages ?? []).length} personal photo${(input.personalImages ?? []).length > 1 ? 's' : ''}`,
                ]
              : []),
          ]
            .filter(Boolean)
            .join(' + ')}. ${
            hasExample
              ? 'Reference image #1 is a finished example crest - replicate its visual language (style, composition, palette, border, flowers, and personal motifs) as instructed above.'
              : ''
          }${
            (input.personalImages ?? []).length > 0
              ? ' For the personal photos, paint the main subject of each as an illustrated element in the crest\'s medium, integrated naturally into the composition. Keep the subjects recognizable but render them in the chosen style (e.g. watercolor washes for botanical_watercolor, engraved line work for vintage_engraving).'
              : ''
          }`.trim(),
        ]
      : []),
    `Avoid: ${[...style.forbidden, 'mockup', 'paper texture'].join(', ')}.`,
    'Return one polished finished wedding crest with the lettering integrated into the artwork.',
  ].join('\n');
}

/**
 * Build a "lettering re-render" prompt used by the result page's
 * small-modification flow. The reference image carries the existing
 * illustration; this prompt only asks the model to re-render the
 * typography described by the latest project settings while keeping
 * everything else identical.
 */
export function compileWeddingTextEditPrompt(input: WeddingPromptRequest) {
  const typography = getWeddingTypography(input.typography);
  const texts = resolveWeddingDisplayTexts(input);
  const inscriptionLines: string[] = [
    `Main inscription: "${texts.headline}" (the largest, centered).`,
  ];
  if (texts.names) {
    inscriptionLines.push(
      `Names line: "${texts.names}" (smaller, below the main inscription).`
    );
  }
  if (texts.date) {
    inscriptionLines.push(
      `Date line: "${texts.date}" (smallest, below the names line).`
    );
  }
  return [
    'Edit the wedding crest shown in the reference image.',
    'Keep the entire illustration - composition, framing, border, ornaments, palette, floral and personal motifs, and all artwork details - exactly as it appears.',
    'Keep the background fully transparent exactly as in the reference image - no backdrop, no paper, no fill color, no shadows.',
    'Replace ONLY the lettering in the crest with the following new typography, in the same centered position:',
    ...inscriptionLines,
    `Lettering style: ${typography.prompt}.`,
    'Text rules: render every inscription exactly as quoted, letter for letter, in the same casing; keep the lettering crisp, evenly spaced and elegantly typeset so it reads clearly; include no other words, letters, numbers, dates, logos, watermarks or symbols anywhere in the image.',
    'Do not change anything else in the design.',
  ].join('\n');
}

export function getWeddingVersions() {
  return {
    promptVersion: WEDDING_PROMPT_VERSION,
    styleVersion: WEDDING_STYLE_VERSION,
    layoutVersion: WEDDING_LAYOUT_VERSION,
  };
}
