#!/bin/sh
set -eu

# Targeted rollback for this P0 pass. It reverses only exact strings introduced
# by this pass, preserving unrelated pre-existing worktree changes.
ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/../.." && pwd)
cd "$ROOT"

python3 - <<'PY'
from pathlib import Path

root = Path('.')
replacements = {
    'src/config/index.ts': [
        ("const DEFAULT_APP_URL = 'https://weddingcrestdesign.com';\n", ''),
        ("process.env.NEXT_PUBLIC_APP_URL?.trim() || DEFAULT_APP_URL", "process.env.NEXT_PUBLIC_APP_URL ?? 'http://localhost:3000'"),
        ("process.env.AUTH_URL?.trim() ||\n    process.env.NEXT_PUBLIC_APP_URL?.trim() ||\n    DEFAULT_APP_URL", "process.env.AUTH_URL || process.env.NEXT_PUBLIC_APP_URL || ''"),
    ],
    'src/core/auth/config.ts': [("https://weddingcrestdesign.com", "https://removegeminiwatermark.org")],
    'src/shared/actions/contact.ts': [("support@weddingcrestdesign.com", "support@removegeminiwatermark.org"), ("Wedding Crest Design", "RemoveGeminiWatermark")],
    'src/shared/blocks/common/built-with.tsx': [("support@weddingcrestdesign.com", "support@removegeminiwatermark.org")],
    'src/shared/lib/seo.ts': [("@WeddingCrestDesign", "@RemoveGeminiWM")],
    'src/app/[locale]/(landing)/blog/[slug]/page.tsx': [("Wedding Crest Design", "RemoveGeminiWatermark")],
    'package.json': [("wedding-crest-design", "remove-gemini-watermark"), ("Wedding Crest Design Team", "RemoveGeminiWatermark Team"), ("wedding-crest", "watermark-remover"), ("wedding-monogram", "gemini"), ("ai-design-tool", "ai-image-tool")],
    'README.md': [("# Wedding Crest Design", "# Remove Gemini Watermark"), ("Create a custom wedding crest, monogram, and stationery identity kit with AI-illustrated artwork and crisp programmatic typography.", "A tool for removing watermarks from images generated by Google Gemini."), (".env.local", ".env.development")],
    'LICENSE': [("Wedding Crest Design Team", "RemoveGeminiWatermark Team")],
    'wrangler.toml.example': [("name = \"wedding-crest-design\"", "name = \"your-app-name\""), ("https://weddingcrestdesign.com", "http://localhost:3000"), ("Wedding Crest Design", "Your App Name")],
    '.env.example': [("https://weddingcrestdesign.com", "http://localhost:3000"), ("replace-with-openssl-rand-base64-32", "REPLACE_WITH_OPENSSL_RAND_BASE64_32")],
}
for locale in ('de','en','fr','it','ko','pt-BR','th','zh'):
    replacements[f'src/config/locale/messages/{locale}/pages/index.json'] = [
        ("Wedding Crest Design — Create a Custom Wedding Crest", "Wedding Crest Design — AI Wedding Crest & Monogram Maker"),
        ("Wedding crest design made personal. Create a custom AI wedding crest with six styles, 12 layouts, curated palettes, editorial typography, and a downloadable SVG identity kit.", "Design a custom wedding crest in minutes. Six styles, 12 layouts, matching color palettes and typography — with full SVG downloads, monograms and mockups. Free to start."),
        ("Create a Wedding Crest Design That Feels Like You", "Create a Wedding Crest That Feels Like You"),
        ("Get One Finished Crest + Full Kit", "Get 3 Crests + Full Kit"),
    ]
    replacements[f'src/config/locale/messages/{locale}/pages/pricing.json'] = [("1 finished crest design per generation", "3 crest candidates per generation"), ("3 regenerations (3 more finished crest designs)", "3 regenerations (9 more crest candidates)")]
    replacements[f'src/config/locale/messages/{locale}/pages/design.json'] = [("Want a fresh design?", "Want a new set?"), ("Crest design {index}", "Candidate {index}")]
    replacements[f'src/config/locale/messages/{locale}/pages/seo.json'] = [("Free accounts can regenerate up to four times; the Wedding Identity Pack adds three more regenerations.", "Unlock the pack to regenerate up to four times.")]
    replacements[f'src/config/locale/messages/{locale}/admin/sidebar.json'] = [("Wedding Crest Design", "RemoveGeminiWatermark")]

for name, pairs in replacements.items():
    p = root / name
    if not p.exists():
        continue
    s = p.read_text()
    for new, old in pairs:
        s = s.replace(new, old)
    p.write_text(s)
print('targeted rollback applied')
PY
